# makefile for Point3Dd

# (C) Bill Lenhart 

# local variables override values from ../Makefile
# Name of this class
CLASS = Point3Dd
USESCLASSES = ../Transform3Dd/Transform3Dd.o

include ../include.mak














