# makefile for Transform4Dd

# (C) Anonymous1 

# local variables override values from ../Makefile
# Name of this class
CLASS = Transform4Dd
USESCLASSES = ../Point4Dd/Point4Dd.o ../Point3Dd/Point3Dd.o ../Transform3Dd/Transform3Dd.o

include ../include.mak














