# makefile for Point3Df

# (C) Bill Lenhart 

# local variables override values from ../Makefile
# Name of this class
CLASS = Point3Df
USESCLASSES = ../Transform3Df/Transform3Df.o

include ../include.mak














