# makefile for Transform3Dd

# (C) Anonymous1 

# local variables override values from ../Makefile
# Name of this class
CLASS = Transform3Dd
USESCLASSES = ../Point3Dd/Point3Dd.o

include ../include.mak














