# makefile for Transform3Df

# (C) Anonymous1 

# local variables override values from ../Makefile
# Name of this class
CLASS = Transform3Df
USESCLASSES = ../Point3Df/Point3Df.o

include ../include.mak














